const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "BGC Dev";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "******";
const retypPassword = "Retype Password";
const name = "Name";
const imageUrl = "imageUrl";
const nameHint = "Mynul Dev";
const forgetPassword = "Forget password";
const login = "Log in";
const signup = "Sign up";
const CreateNewAccount = "or, create a new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const loggedin = "Logged in successfully";
const loggedout = "Loggedout in successfully";
const termAndCond = "Terms And Conditons";
const alreadyHaveAccount = "Already you have an account? ";
const home = "Home",
    topCategories = "Categories",
    cart = "Cart",
    account = "Account";
//For home Page
const searchAnything = "Search Anything...",
    todayDeal = "Todays Deal",
    flashSale = "Flash Sale",
    topsellers = "Top Sellers",
    brand = "Brands",
    toCategories = "To Categories",
    featureCategories = "Feature Categories",
    womenDress = "Womens Dress",
    grilsWatches = "Grils Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    grilsGlasses = "Grils Glasses",
    tShirt = "T-Shirt",
    grilsDress = "Gril Dress",
    featureProduct = "Feature Product";
//For category Page
const categories = "Categories",
    womenClothing = "Women Clothing",
    menClothingFasion = "Men Clothing Fasion",
    comAccess = "Computer & Accessories",
    autoMobile = "Auto Mobile",
    sports = "Sports",
    jewelery = "Jewelery",
    kidtoys = "Kid & Toys",
    cellPhone = "cell Phone",
    funiture = "Funiture";
//For Iteam detailes
const video = "Video",
    reviews = "Reviews",
    sellerpolicy = "Seller Policy",
    returnpolicy = "Return Policy",
    productsyoumaylike = "Products you may also like",
    supportpolicy = "Support Policy";

//For details cart
const wishList = "My Wishlist",
    order = "My Order",
    messagse = "My Messagse",
    oldpass = 'Old passdword',
    newpass = 'New password';
